quadruped:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  lf_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_haa_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  rf_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_haa_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  lh_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_haa_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  rh_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_haa_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}


  lf_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_hfe_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  rf_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_hfe_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  lh_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_hfe_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  rh_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_hfe_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}


  lf_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_kfe_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  lh_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_kfe_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  rh_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_kfe_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
  rf_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_kfe_joint
    pid: {p: 10.0, i: 0.00, d: 0.5}
